### ISSUE TITLE
Unhandled Exception: Instance of 'MsalInitializationException'

### ISSUE THREAD

**Issue by GSPrakashNaidu2** [fabio21/azure_ad_authentication#10]
We are trying to initialize the azure authentication method in an android device, But getting the unhandled exception.   Here is the log:

`D/DART/NATIVE(14813): onMethodCall initialize
W/Telemetry(14813):  [2022-12-27 10:16:49 - thread_name : main, correlation_id : UNSET]  Android 31 Telemetry is disabled because the Telemetry context or configuration is null
W/PublicClientApplicationConfiguration:validateCustomTabRedirectActivity(14813):  [2022-12-27 10:16:49 - thread_name : main, correlation_id : UNSET]  Android 31 Another application com.sample.abcd_mobile is listening for the URL scheme msauth://com.sample.abcd_mobile/xxxxxxxxxxxxxxx
E/flutter (14813): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'MsalInitializationException'
E/flutter (14813): #0      AzureAdAuthentication._initialize (package:azure_ad_authentication/azure_ad_authentication.dart:142:7)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): #1      AzureAdAuthentication.createPublicClientApplication (package:azure_ad_authentication/azure_ad_authentication.dart:34:5)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): #2      _MyAppState.intPca (package:plugin_test_app/main.dart:220:12)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): #3      _MyAppState.getResult (package:plugin_test_app/main.dart:192:33)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): #4      _MyAppState._acquireToken (package:plugin_test_app/main.dart:178:5)
E/flutter (14813): <asynchronous suspension>
E/flutter (14813): 
`

**Comment by fabio21** [comment]
correctly configure the id and the other steps for operation this is wrong
msauth://com.sample.abcd_mobile/xxxxxxxxxxxxxxx
