### ISSUE TITLE
Found 0 accounts

### ISSUE THREAD

**Issue by sjdean** [fabio21/azure_ad_authentication#11]
I cannot get this to work - it is calling the onMethodCall acquireToken, but then seems to end up with Found 0 accounts for this clientId and Found 0 accounts with IdTokens.

On my Pixel 6 Pro, it can find a broker, but on an AVD, it cannot find a broker, however both appear to report the same issue with finding zero accounts.

I would expect at this point a request for login would occur, but it appears it does not.

Logs below:

D/DART/NATIVE(31178): onMethodCall initialize
I/PublicClientApplication:initializeApplication(31178):  [2023-01-22 23:24:53 - thread_name : main, correlation_id : UNSET] Create new public client application. Android 33
D/DART/NATIVE(31178): onMethodCall acquireToken
V/com.microsoft.identity.client.internal.controllers.MSALControllerFactory:powerOptimizationEnabled(31178):  [2023-01-22 23:24:53 - thread_name : Thread-6, correlation_id : UNSET] Is power optimization on? [true] Android 33
V/com.microsoft.identity.client.internal.controllers.MSALControllerFactory:brokerEligible(31178):  [2023-01-22 23:24:53 - thread_name : Thread-6, correlation_id : UNSET] Is the power optimization enabled? [true] Android 33
I/BrokerMsalController(31178):  [2023-01-22 23:24:53 - thread_name : Thread-6, correlation_id : UNSET] Broker Strategies added : ContentProviderStrategy, BoundServiceStrategy, AccountManagerStrategy. Android 33
V/CommandDispatcher:initializeDiagnosticContext(31178):  [2023-01-22 23:24:53 - thread_name : Thread-6, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Initialized new DiagnosticContext Android 33
I/CommandDispatcher:submitSilent:CommandParameters(31178):  [2023-01-22 23:24:53 - {"thread_id":"119","thread_name":"Thread-6","correlation_id":"e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx","x-client-Ver":"1.5.9","x-client-SKU":"MSAL.Android"}] Starting request for correlation id : ##e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx, with PublicApiId : 923 Android 33
I/CommandDispatcher:submitSilent:CommandParameters(31178):  [2023-01-22 23:24:53 - thread_name : Thread-6, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] {"applicationName":"uk.co.my-application","applicationVersion":"1.1.2","clientId":"1a5341c1-dbe4-4504-8837-64dedad3b721","correlationId":"e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx","powerOptCheckEnabled":true,"redirectUri":"msauth://uk.co.my-application/3d1VprSi2EhJ8IXjXOY00s7xFdg%3D","requiredBrokerProtocolVersion":"3.0","sdkType":"MSAL","sdkVersion":"1.5.9"} Android 33
V/CommandDispatcher:initializeDiagnosticContext(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Initialized new DiagnosticContext Android 33
V/EstsTelemetry:createLastRequestTelemetryCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Creating Last Request Telemetry Cache Android 33
V/SharedPreferencesLastRequestTelemetryCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Init: SharedPreferencesLastRequestTelemetryCache Android 33
V/EstsTelemetry(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Ests Telemetry cache has been initialized properly. Android 33
V/LoadAccountCommand:execute(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Executing with controller: LocalMSALController Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loading Accounts... Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loading Accounts...(no arg) Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loading Accounts + keys... Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Returning [0] Accounts w/ keys... Android 33
I/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found [0] Accounts... Android 33
V/AbstractAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Account lookup filtered by home_account_id? [false]
V/AbstractAccountCredentialCache(31178): Account lookup filtered by realm? [false] Android 33
V/AbstractAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found [0] matching accounts Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found [0] matching Accounts... Android 33
V/MsalOAuth2TokenCache:getAccounts(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found 0 accounts for this environment Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loading Credentials... Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loading Credentials with keys... Android 33
V/SharedPreferencesAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Loaded [0] Credentials... Android 33
V/AbstractAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Credential lookup filtered by home_account_id? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by realm? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by target? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by clientId? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by credential type? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by auth scheme? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by requested claims? [false] Android 33
V/AbstractAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Credential lookup filtered by home_account_id? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by realm? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by target? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by clientId? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by credential type? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by auth scheme? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by requested claims? [false] Android 33
V/AbstractAccountCredentialCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Credential lookup filtered by home_account_id? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by realm? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by target? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by clientId? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by credential type? [true]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by auth scheme? [false]
V/AbstractAccountCredentialCache(31178): Credential lookup filtered by requested claims? [false] Android 33
V/MsalOAuth2TokenCache:getAccounts(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found 0 accounts for this clientId Android 33
V/MsalOAuth2TokenCache:getAccountsWithAggregatedAccountData(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Found 0 accounts with IdTokens Android 33
V/LoadAccountCommand:execute(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Executing with controller: BrokerMsalController Android 33
I/BrokerOperationExecutor:getAccounts(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Executing with IIpcStrategy: ContentProviderStrategy Android 33
I/com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategyMSAL_GET_ACCOUNTS(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Request to BrokerContentProvider for uri path /getAccounts Android 33
I/com.microsoft.identity.common.internal.broker.ipc.ContentProviderStrategyMSAL_GET_ACCOUNTS(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Received successful result from Broker Content Provider. Android 33
I/CommandDispatcher:submitSilent(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Completed silent request as owner for correlation id : **e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx, with the status : SUCCESS is cacheable : false Android 33
V/SharedPreferencesLastRequestTelemetryCache(31178):  [2023-01-22 23:24:53 - thread_name : pool-14-thread-2, correlation_id : e213c5ae-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Saving Last Request Telemetry to cache... Android 33

**Comment by fabio21** [comment]
I did the implementation of the new masl in the package you could test, my test with android 33 are working properly, and has not yet been published post I'm updated, the version of IOS and MacOs

**Comment by fabio21** [comment]
update msal 4.+ android and  ios, macos 1.2.9
