### ISSUE TITLE
Browser Login Window not Opening

### ISSUE THREAD

**Issue by sjdean** [fabio21/azure_ad_authentication#12]
With the "WARNING" level set, we get in the logs:

D/DART/NATIVE(26180): onMethodCall initialize
D/DART/NATIVE(26180): onMethodCall acquireToken

And then nothing else.

Line 44 in azure_ad_authentication.dart is reached:

final String? json = await _channel.invokeMethod('acquireToken', res);

Adding some additional debugging, I can see that the acqureToken() function on line 148 of MsalHandlerImpl.kt appears to go run through fine, but I don't get any windows to sign in.

**Comment by fabio21** [comment]
I did the implementation of the new masl in the package you could test, my test with android 33 are working properly, and has not yet been published post I'm updated, the version of IOS and MacOs

**Comment by fabio21** [comment]
new update android  msal 4.+ and ios, macos 1.2.9
