### ISSUE TITLE
MsalException is thrown for custom policy authorization url in acquireToken 

### ISSUE THREAD

**Issue by mbhusari** [fabio21/azure_ad_authentication#14]
I am trying to integrate a custom profile for iOS by providing a custom profile's authority, redirectUri, and scopes for my B2C application. But getting MsalException in acquireToken call. Followed all other steps mentioned in the plugin integration steps. 

static const String _authority = "https://xxxxxx.b2clogin.com/<domain>/<policy_name>/oauth2/v2.0/authorize"
static const String _redirectUriIos = "msauth.<Bundle_id>://auth";
static const List<String> kScopes = [
    "https://<domain>/<Client_id>/Read",
    "https://<domain>/<Client_id>/Write",
  ];

Device: 
iOS : iOS15.5
Device: iPhone 12 Pro Simulator
version: azure_ad_authentication: ^1.0.5

**Comment by fabio21** [comment]
use only for macos  redirect
