### ISSUE TITLE
Configuration Issue

### ISSUE THREAD

**Issue by Mohamed-Gibreel** [fabio21/azure_ad_authentication#18]
Hello all,

I am trying to setup this package but I keep getting this error: Unhandled Exception: Error initializing client. Please ensure correctly configuration supplied.

I have followed the guide shown in pub.dev and repeated it 3 times now, I checked the AndroidManifest.xml file, the config.json file build.gradle etc... but I still keep getting this error, any ideas ?

**Comment by fabio21** [comment]
**this name for the JSON file**  =>  msal_default_config.json

**You generated your key correctly**
keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64

**Comment by govarthananve** [comment]
@fabio21 Can we use exactly the same ~/.android/debug.keystore or need to use the .jks file like /android/app/Keystore/adtest.jks file?
