### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

### ISSUE THREAD

**Issue by thye1997** [fabio21/azure_ad_authentication#4]
E/AndroidRuntime(10476): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime(10476): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfigurationInternal(PublicClientApplicationConfigurationFactory.java:96)
E/AndroidRuntime(10476): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:70)
E/AndroidRuntime(10476): 	at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:459)
E/AndroidRuntime(10476): 	at java.lang.Thread.run(Thread.java:764)

Anyone facing the problem above when running android app?

**Comment by joelsongsouzza** [comment]
I'm facing the same error.

**Comment by thye1997** [comment]
Yes i resolved it
