### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by bdlindsay** [fabio21/azure_ad_authentication#7]
I believe there are some missing keys in the readme that the android MSAL library expects in the default configuration file and the app will crash when attempting to sign in when they are not present.

Here's a link to the current default config from the android MSAL library: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/res/raw/msal_default_config.json

**Comment by fabio21** [comment]
update doc
