### ISSUE TITLE
Is it possible to use this library with a flutter web app only ? As in, not android host platform. 

### ISSUE THREAD

**Issue by DanGM321** [fabio21/azure_ad_authentication#9]
I just want to develop a flutter app that can authenticate against azure ad. 
I have been looking for auth libraries but they all talk about updating manifest, build gradle etc. I dont need anything else , just a web app. 
Is it possible to use this library with a flutter web app only ????

I have this exception error : MissingPluginException(No implementation found for method initialize on channel azure_ad_authentication)

**Comment by fabio21** [comment]
does not yet have web support only android, ios, macOs
